language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4
before_install:
  - sudo apt-get update -qq
  - cabal update
install:
  - sudo apt-get install -y libblas-dev
    # Cabal for GHC 7.4 is too ancient
  - if ghc -V | grep 7.4; then cabal install cabal-install; fi
    # for some reason this has to be done after cabal-install is installed
  - export PATH="$HOME/.cabal/bin:$PATH"
  - cabal install --enable-tests --only-dependencies
script:
  - cabal configure -v --enable-tests
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist
  - cabal install dist/*.tar.gz
