language: haskell
ghc:
  - 8.0.2
  - 8.8.1
    # 8.10.1 is not possible because cabal-install doesn't yet support base-4.14.0.0
before_install:
  - sudo apt-get update -qq
  - cabal update
install:
  - sudo apt-get install -y libblas-dev
  - cabal install --enable-tests --only-dependencies
script:
  - cabal configure -v --enable-tests
  - cabal build
  - cabal test --show-details always
    # cabal-install 0.14 doesn't have `--show-details streaming`
  - cabal check
  - cabal sdist
    # --run-tests did not exist until ~0.18
  - cabal install --enable-tests --run-tests dist/*.tar.gz ||
    cabal install --enable-tests             dist/*.tar.gz
