# This makefile is only needed for developing or otherwise modifying the
# package.  For users of the package, simply use Cabal.
.POSIX:
.SUFFIXES:
DOCDIR=dist/doc/html/blas-hs
REMOTE=git@github.com:Rufflewind/blas-hs

all: build

clean:
	rm -f src/Blas/Primitive/blas.h                     \
	      src/Blas/Primitive/Safe_.chs                  \
	      src/Blas/Primitive/Safe.hs                    \
	      src/Blas/Primitive/Unsafe_.chs                \
	      src/Blas/Primitive/Unsafe.hs                  \
	      src/Blas/Generic/Safe.hs                      \
	      src/Blas/Generic/Unsafe.hs                    \
	      src/Blas/Specialized/Float/Safe.hs            \
	      src/Blas/Specialized/Float/Unsafe.hs          \
	      src/Blas/Specialized/Double/Safe.hs           \
	      src/Blas/Specialized/Double/Unsafe.hs         \
	      src/Blas/Specialized/ComplexFloat/Safe.hs     \
	      src/Blas/Specialized/ComplexFloat/Unsafe.hs   \
	      src/Blas/Specialized/ComplexDouble/Safe.hs    \
	      src/Blas/Specialized/ComplexDouble/Unsafe.hs
	cabal clean

build:                                                      \
    src/Blas/Primitive/blas.h                               \
    src/Blas/Primitive/Safe_.chs                            \
    src/Blas/Primitive/Safe.hs                              \
    src/Blas/Primitive/Unsafe_.chs                          \
    src/Blas/Primitive/Unsafe.hs                            \
    src/Blas/Generic/Safe.hs                                \
    src/Blas/Generic/Unsafe.hs                              \
    src/Blas/Specialized/Float/Safe.hs                      \
    src/Blas/Specialized/Float/Unsafe.hs                    \
    src/Blas/Specialized/Double/Safe.hs                     \
    src/Blas/Specialized/Double/Unsafe.hs                   \
    src/Blas/Specialized/ComplexFloat/Safe.hs               \
    src/Blas/Specialized/ComplexFloat/Unsafe.hs             \
    src/Blas/Specialized/ComplexDouble/Safe.hs              \
    src/Blas/Specialized/ComplexDouble/Unsafe.hs
	cabal build

doc: build
	cabal haddock

doc-upload: doc $(DOCDIR)/.git/config
	cd $(DOCDIR)                                        \
	  && git add -A                                     \
	  && git commit --amend -q -m Autogenerated         \
	  && git push -f origin master:gh-pages

$(DOCDIR)/.git/config:
	mkdir -p $(DOCDIR)
	cd $(DOCDIR)                                        \
	  && git init                                       \
	  && git config user.name Bot                       \
	  && git config user.email "<>"                     \
	  && git commit -m _ --allow-empty                  \
	  && git remote add origin $(REMOTE)

# download the header from Netlib
src/Blas/Primitive/blas.h:
	mkdir -p src/Blas/Primitive
	curl >$@ -L http://netlib.org/clapack/CLAPACK-3.1.1.1/BLAS/WRAP/cblas.h

src/Blas/Primitive/Safe.hs:                                 \
    tools/post-process                                      \
    src/Blas/Primitive/blas.h                               \
    src/Blas/Primitive/Safe_.chs
	c2hs blas.h src/Blas/Primitive/Safe_.chs
	tools/post-process src/Blas/Primitive/Safe_.hs
	mv src/Blas/Primitive/Safe_.hs src/Blas/Primitive/Safe.hs

src/Blas/Primitive/Unsafe.hs:                               \
    tools/post-process                                      \
    src/Blas/Primitive/blas.h                               \
    src/Blas/Primitive/Unsafe_.chs
	c2hs blas.h src/Blas/Primitive/Unsafe_.chs
	tools/post-process src/Blas/Primitive/Unsafe_.hs
	mv src/Blas/Primitive/Unsafe_.hs src/Blas/Primitive/Unsafe.hs

# trailing underscore is to prevent Cabal from running c2hs on them
src/Blas/Primitive/Safe_.chs                                \
src/Blas/Primitive/Unsafe_.chs:                             \
    tools/Common.hs                                         \
    tools/generate-ffi
	mkdir -p src/Blas/Primitive
	cd tools && ./generate-ffi

src/Blas/Generic/Safe.hs                                    \
src/Blas/Generic/Unsafe.hs                                  \
src/Blas/Specialized/Float/Safe.hs                          \
src/Blas/Specialized/Float/Unsafe.hs                        \
src/Blas/Specialized/Double/Safe.hs                         \
src/Blas/Specialized/Double/Unsafe.hs                       \
src/Blas/Specialized/ComplexFloat/Safe.hs                   \
src/Blas/Specialized/ComplexFloat/Unsafe.hs                 \
src/Blas/Specialized/ComplexDouble/Safe.hs                  \
src/Blas/Specialized/ComplexDouble/Unsafe.hs:               \
    tools/Common.hs                                         \
    tools/generate-interface
	mkdir -p src/Blas/Generic                           \
	         src/Blas/Specialized/Float                 \
	         src/Blas/Specialized/Double                \
	         src/Blas/Specialized/ComplexFloat          \
	         src/Blas/Specialized/ComplexDouble
	cd tools && ./generate-interface
