#!/bin/sh
#
# Usage: rpp [FILE]
#
# A simple preprocessor that uses Ruby process the text files.  The entire
# document is treated as one Ruby string in the here-document syntax, but
# without the beginning or end delimiters.
#
# If `FILE` is not provided or is a hyphen (`-`), then the standard input is
# used as input.  Otherwise `FILE` is used as input.
#
# Within the file, the filename of the input file can be accessed via a Ruby
# variable named `FILE`.
#
if [ -n "${1+x}" ]
then
    FILE="$1"
else
    FILE=-
fi
EOF=A_LONG_AND_ARBITRARY_EOF_MARKER_FOR_RPP
{
    cat <<EOF
FILE = ARGV[0] if ARGV.size >= 1
print <<$EOF[0..-2]
EOF
    cat "$FILE"
    CAT_FAIL=$?
    echo
    echo "$EOF"
    if [ $CAT_FAIL -ne 0 ]
    then
        printf >&2 '%s\n' "$0: can't read file"
        exit $CAT_FAIL
    fi
} | ruby - "$@"
