#!/bin/sh
if [ -n "${1+x}" ]
then
    FILE="$1"
else
    FILE=-
fi
EOF=A_LONG_AND_ARBITRARY_EOF_MARKER_FOR_RPP
{
    cat <<EOF
FILE = ARGV[0] if ARGV.size >= 1
print <<$EOF[0..-2]
EOF
    cat "$FILE"
    CAT_FAIL=$?
    echo
    echo "$EOF"
    if [ $CAT_FAIL -ne 0 ]
    then
        printf >&2 '%s\n' "$0: can't read file"
        exit $CAT_FAIL
    fi
} | ruby - "$@"
